server:
  contextPath: /auth
  port: 8082
  use-forward-headers: true
  
security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://port-8082.Ubuntu14-04-reinierrg92695293.codeanyapp.com/auth/user_info
#      userInfoUri: http://localhost:8082/auth/user_info
#      user-info-uri: http://ubuntu14-04-reinierrg92695293.codeanyapp.com:8082/auth/user_info
#      user-info-uri: http://localhost:8082/auth/user_info
      
logging:
  level:
    org:
      springframework:
        security: DEBUG
