server:
    port: 8081
    context-path: /ui
    session:
      cookie:
        name: UISESSION
    use-forward-headers: true
    
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: example-client-id
      clientSecret: secret
      access-token-uri: http://port-8082.Ubuntu14-04-reinierrg92695293.codeanyapp.com/auth/token
      user-authorization-uri: http://port-8082.Ubuntu14-04-reinierrg92695293.codeanyapp.com/auth/authorize
    resource:
      user-info-uri: http://port-8082.Ubuntu14-04-reinierrg92695293.codeanyapp.com/auth/user_info
      
spring:
  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
